### ISSUE TITLE
Not working with latest bungeecord

### ISSUE THREAD

**Issue by RedSparr0w** [DaniFoldi/BungeeGUI#75]
BungeeCord version: `git:BungeeCord-Bootstrap:1.17-R0.1-SNAPSHOT:ad50fc9:1585`
Protocolize version: `protocolize-plugin version 1.7.0-SNAPSHOT:605`
BungeeGUI version: `1.2.5`

When running on latest BungeeCord, Plugin fails to start, I am getting the following error:
```
SEVERE
Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@30865a90, id=0, owner=com.danifoldi.bungeegui.main.BungeeGuiPlugin@30272916, task=com.danifoldi.bungeegui.main.PlaceholderHandler$$Lambda$174/0x0000000840255440@6134ac4a, delay=1000, period=5000, running=true) encountered an exception
Console
java.lang.NoSuchMethodError: 'java.util.Map net.md_5.bungee.api.ProxyServer.getServersCopy()'
at com.danifoldi.bungeegui.main.PlaceholderHandler.lambda$registerBuiltins$2(PlaceholderHandler.java:110)
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by DaniFoldi** [comment]
Hi!

Thanks for the bug report. I was using Waterfall to test the plugin, and `getServersCopy` is a method they added to the api. Please test with 1.2.6 which I will release later today. Let me know if there's anything else that I missed.

**Comment by RedSparr0w** [comment]
Thanks for the quick response/update!

I downloaded the `1.2.6` version and getting the following errors:

_NOTE: Not sure why it says loading `1.2.4`, as it was definitely the `1.2.6` version that I downloaded._

```cmd
[BungeeGUI] -------------------------------------------
[BungeeGUI]
[BungeeGUI] Loading BungeeGUI version 1.2.4
[BungeeGUI]
[BungeeGUI] -------------------------------------------
WARNING
Exception encountered when loading plugin: BungeeGUI
Console
java.lang.NoSuchMethodError: 'java.util.Map net.md_5.bungee.api.ProxyServer.getServersCopy()'
at com.danifoldi.bungeegui.main.PlaceholderHandler.registerBuiltins(PlaceholderHandler.java:321)
at com.danifoldi.bungeegui.main.BungeeGuiLoader.load(BungeeGuiLoader.java:66)
at com.danifoldi.bungeegui.main.BungeeGuiPlugin.onEnable(BungeeGuiPlugin.java:24)
at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:287)
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
SEVERE
Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@2c1dc8e, id=0, owner=com.danifoldi.bungeegui.main.BungeeGuiPlugin@450794b4, task=com.danifoldi.bungeegui.main.PlaceholderHandler$$Lambda$174/0x0000000840255440@b273a59, delay=1000, period=5000, running=true) encountered an exception
Console
java.lang.NoSuchMethodError: 'java.util.Map net.md_5.bungee.api.ProxyServer.getServersCopy()'
at com.danifoldi.bungeegui.main.PlaceholderHandler.lambda$registerBuiltins$2(PlaceholderHandler.java:110)
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
```

Seems that there's 2 other places that need updating:
![image](https://user-images.githubusercontent.com/7288322/122525270-2f639480-d06d-11eb-97ca-a678284fc0c8.png)

**Comment by DaniFoldi** [comment]
Hey,

I shouldn't have left releasing until the evening, or at least until today morning. Regardless, here is a pre-release for you to try, this time I'm mildly confident that it's the correct jar, with all instances fixed. [link to wetranswer download because github doesnt let you upload .jars to issues, will expire in a week](https://we.tl/t-9No6AseTl9)

Note, it will complain about not being the latest version, ignore that.

Let me know if I still missed something and should start using IntelliJ's find in files feature.

**Comment by RedSparr0w** [comment]
Perfect!
Thank you for the help 👍
